import MOCK_DATA from "./MOCK_DATA.json";

let initState = {
  trips: {},
  vehicles: {
    url: "vehicles",
    title: "Vehicles",
    currentPage: 0,
    data: {
      vehcileId: "",
      regNo: "",
      vehcileType: "",
      chasisNo: "",
      builtType: "",
      purchaseDate: "",
      manufactureDate: "",
      tyres: 0,
      details: "",
      drivers: [],
      deviceId: "",
      enable: true,
      dateCreated: "",
      dateUpdated: "",
    },
    apiCallData: MOCK_DATA,
    apiData: MOCK_DATA,
    table: [
      { id: "regNo", name: "Registration number", sort: false },
      { id: "vehcileType", name: "Vehicle Type", sort: false },
      { id: "builtType", name: "Built type", sort: false },
      { id: "tyres", name: "Tyres", sort: false },
      { id: "enable", name: "Status", sort: false },
      { id: "dateCreated", name: "Created on", sort: false },
    ],
    form: [
      {
        name: "regNo",
        type: "text",
        label: "Registartion Number",
        placeHolder: "CA 12 1098",
        value: "",
        isRequired: true,
      },
      {
        name: "vehcileType",
        type: "select",
        label: "Vehcile Type",
        placeHolder: "",
        options: [
          { value: "", label: "Select Vehcile" },
          { value: "chocolate", label: "Chocolate" },
          { value: "strawberry", label: "Strawberry" },
          { value: "vanilla", label: "Vanilla" },
        ],
        value: "",
        isRequired: true,
      },
      {
        name: "chasisNo",
        type: "text",
        label: "Chasis Number",
        placeHolder: "AsxpJH678754FD",
        value: "",
        isRequired: true,
      },
      {
        name: "builtType",
        type: "text",
        label: "Built Type",
        placeHolder: "Mercedes 12 Tyre",
        value: "",
      },
      {
        name: "purchaseDate",
        type: "date",
        label: "Date of Purchase",
        placeHolder: "",
        value: "",
      },
      {
        name: "manufactureDate",
        type: "date",
        label: "Date of Manufacture",
        placeHolder: "",
        value: "",
      },
      {
        name: "tyres",
        type: "number",
        label: "Total Tyres",
        placeHolder: "4",
        value: 0,
      },
      {
        name: "details",
        type: "text",
        label: "Details",
        placeHolder: "120 Ton capacity,12 tyres,multi-axle",
        value: "",
        isMulti: true,
      },
      {
        name: "drivers",
        type: "select",
        label: "Assign Drivers",
        placeHolder: "",
        options: [
          { value: "", label: "Select Vehcile" },
          { value: "chocolate", label: "Chocolate" },
          { value: "strawberry", label: "Strawberry" },
          { value: "vanilla", label: "Vanilla" },
        ],
        value: "",
        isMulti: true,
        isRequired: true,
      },
      {
        name: "deviceId",
        type: "select",
        label: "Assign Device",
        placeHolder: "",
        options: [
          { value: "", label: "Select Vehcile" },
          { value: "chocolate", label: "Chocolate" },
          { value: "strawberry", label: "Strawberry" },
          { value: "vanilla", label: "Vanilla" },
        ],
        value: "",
        isAdminOnly: true,
      },
      {
        name: "enable",
        type: "checkbox",
        label: "Active",
        placeHolder: "0",
        value: true,
      },
      {
        name: "activationDate",
        type: "date",
        label: "Activation Date",
        placeHolder: "",
        value: "",
      },
    ],
    mobileTable: {
      left: {
        avatar: { static: "./assets/images/owner.png", dynamic: "vehcileId" },
        title: null,
        sub: null,
      },
      content: {
        titleId: "regNo",
        subTitles: ["vehcileType", "builtType"],
      },
      rightId: null,
    },
    mobileDetails: [
      {
        left: {
          avatar: { static: "./assets/images/owner.png", dynamic: "vehcileId" },
          title: null,
          sub: null,
        },
        content: {
          titleId: "regNo",
          subTitles: ["vehcileType", "builtType"],
        },
        rightId: null,
        list: [
          { label: "Vehcile type", value: "vehcileType" },
          { label: "Chasis Number", value: "chasisNo" },
          { label: "Total Tyres", value: "tyres" },
          { label: "Status", value: "enable", isBoolenan: true },
          {
            label: "Date of Manufacture",
            value: "manufactureDate",
            isDate: true,
          },
          { label: "Date of Purchase", value: "purchaseDate", isDate: true },
          { label: "", value: "details" },
        ],
      },
    ],
  },
  drivers: {
    url: "drivers",
    title: "Drivers",
    currentPage: 0,
    data: {
      vehcileId: "",
      regNo: "",
      vehcileType: "",
      chasisNo: "",
      builtType: "",
      purchaseDate: "",
      manufactureDate: "",
      tyres: 0,
      details: "",
      drivers: [],
      deviceId: "",
      enable: true,
      activationDate: "",
      dateCreated: "",
      dateUpdated: "",
    },
    apiCallData: [],
    apiData: [],
    table: [
      { id: "regNo", name: "Registration number", sort: false },
      { id: "vehcileType", name: "Vehicle Type", sort: false },
      { id: "builtType", name: "Built type", sort: false },
      { id: "tyres", name: "Tyres", sort: false },
      { id: "enable", name: "Status", sort: false },
      { id: "dateCreated", name: "Created on", sort: false },
    ],
    form: [
      {
        name: "regNo",
        type: "text",
        label: "Registartion Number",
        placeHolder: "CA 12 1098",
        value: "",
        isRequired: true,
      },
      {
        name: "vehcileType",
        type: "select",
        label: "Vehcile Type",
        placeHolder: "",
        options: [
          { value: "", label: "Select Vehcile" },
          { value: "chocolate", label: "Chocolate" },
          { value: "strawberry", label: "Strawberry" },
          { value: "vanilla", label: "Vanilla" },
        ],
        value: "",
        isRequired: true,
      },
      {
        name: "chasisNo",
        type: "text",
        label: "Chasis Number",
        placeHolder: "AsxpJH678754FD",
        value: "",
        isRequired: true,
      },
      {
        name: "builtType",
        type: "text",
        label: "Built Type",
        placeHolder: "Mercedes 12 Tyre",
        value: "",
      },
      {
        name: "purchaseDate",
        type: "date",
        label: "Date of Purchase",
        placeHolder: "",
        value: "",
      },
      {
        name: "manufactureDate",
        type: "date",
        label: "Date of Manufacture",
        placeHolder: "",
        value: "",
      },
      {
        name: "tyres",
        type: "number",
        label: "Total Tyres",
        placeHolder: "4",
        value: 0,
      },
      {
        name: "details",
        type: "text",
        label: "Details",
        placeHolder: "120 Ton capacity,12 tyres,multi-axle",
        value: "",
      },
      {
        name: "drivers",
        type: "select",
        label: "Assign Drivers",
        placeHolder: "",
        options: [
          { value: "", label: "Select Vehcile" },
          { value: "chocolate", label: "Chocolate" },
          { value: "strawberry", label: "Strawberry" },
          { value: "vanilla", label: "Vanilla" },
        ],
        value: "",
        isMulti: true,
        isRequired: true,
      },
      {
        name: "deviceId",
        type: "select",
        label: "Assign Device",
        placeHolder: "",
        options: [
          { value: "", label: "Select Vehcile" },
          { value: "chocolate", label: "Chocolate" },
          { value: "strawberry", label: "Strawberry" },
          { value: "vanilla", label: "Vanilla" },
        ],
        value: "",
        isRequired: true,
      },
      {
        name: "enable",
        type: "checkbox",
        label: "Active",
        placeHolder: "0",
        value: true,
      },
      {
        name: "activationDate",
        type: "date",
        label: "Activation Date",
        placeHolder: "",
        value: "",
      },
    ],
    mobileTable: {
      left: {
        avatar: { static: "./assets/images/owner.png", dynamic: "vehcileId" },
        title: null,
        sub: null,
      },
      content: {
        titleId: "regNo",
        subTitles: ["vehcileType", "builtType"],
      },
      rightId: null,
    },
    mobileDetails: [
      {
        left: {
          avatar: { static: "./assets/images/owner.png", dynamic: "vehcileId" },
          title: null,
          sub: null,
        },
        content: {
          titleId: "regNo",
          subTitles: ["vehcileType", "builtType"],
        },
        rightId: null,
        list: [
          { label: "Vehcile type", value: "vehcileType" },
          { label: "Chasis Number", value: "chasisNo" },
          { label: "Total Tyres", value: "tyres" },
          { label: "Status", value: "enable", isBoolenan: true },
          {
            label: "Date of Manufacture",
            value: "manufactureDate",
            isDate: true,
          },
          { label: "Date of Purchase", value: "purchaseDate", isDate: true },
          { label: "", value: "details" },
        ],
      },
    ],
  },
  owners: {
    url: "owners",
    title: "Owners",
    currentPage: 0,
    data: {
      ownerId: "",
      firstName: "",
      lastName: "",
      avatar: "",
      ownerName: "",
      regNo: "",
      address: "",
      estbDate: "",
      country: "",
      state: "",
      city: "",
      enable: true,
      activationDate: "",
      dateCreated: "",
      dateUpdated: "",
    },
    apiCallData: [],
    apiData: [],
    table: [
      { id: "ownerName", name: "Name", sort: false },
      { id: "regNo", name: "Registration", sort: false },
      { id: "city", name: "City", sort: false },
      { id: "state", name: "State", sort: false },
      { id: "country", name: "Country", sort: false },
      { id: "enable", name: "Status", sort: false },
      { id: "dateCreated", name: "Created on", sort: false },
    ],
    form: [
      {
        name: "firstName",
        type: "text",
        label: "First Name",
        placeHolder: "Jhon",
        value: "",
        isRequired: true,
      },
      {
        name: "lastName",
        type: "text",
        label: "Last Name",
        placeHolder: "Doe",
        value: "",
        isRequired: true,
      },
      {
        name: "ownerName",
        type: "text",
        label: "Owner Name",
        placeHolder: "ABC Transport Company",
        value: "",
        isRequired: true,
      },
      {
        name: "regNo",
        type: "text",
        label: "Registartion Number",
        placeHolder: "ABC Transport Company",
        value: "",
      },
      {
        name: "address",
        type: "text",
        label: "Address",
        placeHolder: "Street no 10,Ontario,Canada",
        value: "",
      },
      {
        name: "estbDate",
        type: "date",
        label: "Date of Establishment",
        placeHolder: "",
        value: "",
      },
      {
        name: "country",
        type: "select",
        label: "Country",
        placeHolder: "",
        options: [
          { value: "", label: "Select Vehcile" },
          { value: "chocolate", label: "Chocolate" },
          { value: "strawberry", label: "Strawberry" },
          { value: "vanilla", label: "Vanilla" },
        ],
        value: "",
      },
      {
        name: "state",
        type: "select",
        label: "State",
        placeHolder: "",
        options: [
          { value: "", label: "Select Vehcile" },
          { value: "chocolate", label: "Chocolate" },
          { value: "strawberry", label: "Strawberry" },
          { value: "vanilla", label: "Vanilla" },
        ],
        value: "",
      },
      {
        name: "city",
        type: "select",
        label: "City",
        placeHolder: "",
        options: [
          { value: "", label: "Select Vehcile" },
          { value: "chocolate", label: "Chocolate" },
          { value: "strawberry", label: "Strawberry" },
          { value: "vanilla", label: "Vanilla" },
        ],
        value: "",
      },
      {
        name: "enable",
        type: "checkbox",
        label: "Active",
        placeHolder: "0",
        value: true,
      },
      {
        name: "activationDate",
        type: "date",
        label: "Activation Date",
        placeHolder: "",
        value: "",
      },
    ],
  },
  tickets: {},
  payments: {},
  notifications: {},
};

export { initState };
